[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test* *Test
python_functions = test_* *test
testpaths = apps
addopts =
    --strict-markers
    -v
    --tb=short
    --maxfail=1