[pytest]
# Укажите путь к вашему файлу настроек (замените 'core' на название папки с settings.py)
DJANGO_SETTINGS_MODULE = config.settings

# Шаблоны названий файлов с тестами
python_files = tests.py test_*.py *_tests.py

# (Опционально) Чтобы не писать @pytest.mark.django_db везде
# addopts = --nomigrations
